# -*- coding: utf-8 -*-
"""WEEK-16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8uK0XFwK0b05DVK8gk3ZWOZR2fbysZ5

**16. MEDICAL INSURANCE COST ANALYSIS & PREDICTION SYSTEM
COMPLETE FINAL GOOGLE COLAB PROJECT**

**OBJECTIVE 1 : IMPORT LIBRARIES**
"""

import pandas as pd
import numpy as np
# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
# Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error,
    accuracy_score,
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score
)
import warnings
warnings.filterwarnings('ignore')
print("Libraries Imported Successfully")

"""**OBJECTIVE 2 : LOAD DATASET**"""

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/insurance.csv')
print("Dataset Loaded Successfully")

"""**DISPLAY DATASET**"""

print(df.head())

"""**DATASET INFORMATION**"""

print(df.info())

"""**DATASET SHAPE**"""

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

"""**COLUMN NAMES**"""

print(df.columns)

"""**OBJECTIVE 3 : DATA CLEANING & PREPROCESSING**

**MISSING VALUES**
"""

print(df.isnull().sum())

"""**CHECK DUPLICATES**"""

print("Duplicate Records :", df.duplicated().sum())

"""**REMOVE DUPLICATES**"""

df = df.drop_duplicates()
print("Duplicates Removed Successfully")

"""**CHECK DATA TYPES**"""

print(df.dtypes)

"""**ENCODE CATEGORICAL VARIABLES**"""

le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])
df['region'] = le.fit_transform(df['region'])
print("Encoding Completed")

"""**DISPLAY CLEANED DATASET**"""

print(df.head())

"""**OBJECTIVE 4 : DESCRIPTIVE STATISTICS**"""

print(df.describe())

"""**AVERAGE VALUES**"""

print("Average Age :", df['age'].mean())
print("Average BMI :", df['bmi'].mean())
print("Average Children :", df['children'].mean())
print("Average Charges :", df['charges'].mean())

"""**OBJECTIVE 5 : INSURANCE COST ANALYSIS**"""

print(df.groupby('smoker')['charges'].mean())
print(df.groupby('sex')['charges'].mean())

"""**BMI CATEGORY CREATION**"""

def bmi_category(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif bmi < 25:
        return 'Normal'
    elif bmi < 30:
        return 'Overweight'
    else:
        return 'Obese'
df['BMI_Category'] = df['bmi'].apply(bmi_category)
print(df.head())

"""**BMI CATEGORY ANALYSIS**"""

print(df.groupby('BMI_Category')['charges'].mean())

"""**AGE GROUP CREATION**"""

bins = [18, 30, 45, 60, 100]
labels = ['Young', 'Adult', 'Middle Age', 'Senior']
df['Age_Group'] = pd.cut(df['age'], bins=bins, labels=labels)
print(df.head())

"""**AGE GROUP ANALYSIS**"""

print(df.groupby('Age_Group')['charges'].mean())

"""**OBJECTIVE 6 : GROUP BASED ANALYSIS**"""

print(df.groupby('region')['charges'].mean())
print(df.groupby('children')['charges'].mean())

"""**OBJECTIVE 7 : RELATIONSHIP ANALYSIS**"""

print(df.corr(numeric_only=True))

"""**OBJECTIVE 8 : DATA VISUALIZATION**

**HISTOGRAM - AGE**
"""

fig = px.histogram(
    df,
    x='age',
    title='Age Distribution',
    color_discrete_sequence=['#C0504D']
)
fig.show()

"""**HISTOGRAM - BMI**"""

fig = px.histogram(
    df,
    x='bmi',
    title='BMI Distribution',
    color_discrete_sequence=['#7B1C1C']
)
fig.show()

"""**HISTOGRAM - CHARGES**"""

fig = px.histogram(
    df,
    x='charges',
    title='Insurance Charges Distribution',
    color_discrete_sequence=['#A52A2A']
)
fig.show()

"""**SCATTER PLOT - AGE VS CHARGES**"""

fig = px.scatter(
    df,
    x='age',
    y='charges',
    color='smoker',
    title='Age vs Insurance Charges'
)
fig.show()

"""**SCATTER PLOT - BMI VS CHARGES**"""

fig = px.scatter(
    df,
    x='bmi',
    y='charges',
    color='smoker',
    title='BMI vs Insurance Charges'
)
fig.show()

"""**BAR CHART - REGION VS CHARGES**"""

region_charges = df.groupby('region')['charges'].mean().reset_index()
fig = px.bar(
    region_charges,
    x='region',
    y='charges',
    title='Region Wise Average Charges',
    color='charges',
    color_continuous_scale='Reds'
)
fig.show()

"""**BAR CHART - SMOKER VS NON-SMOKER**"""

smoker_charges = df.groupby('smoker')['charges'].mean().reset_index()
fig = px.bar(
    smoker_charges,
    x='smoker',
    y='charges',
    title='Smoker vs Non-Smoker Charges',
    color='charges',
    color_continuous_scale='Reds'
)
fig.show()

"""**BOX PLOT**"""

fig = px.box(
    df,
    x='smoker',
    y='charges',
    title='Smoker vs Charges'
)
fig.show()

"""**HEATMAP**"""

fig = px.imshow(
    df[['age','sex','bmi','children','smoker','region','charges']].corr(),
    title='Correlation Heatmap',
    color_continuous_scale='Reds'
)
fig.show()

"""**PIE CHART - SMOKER DISTRIBUTION**"""

fig = px.pie(
    df,
    names='smoker',
    title='Smoker Distribution'
)
fig.show()

"""**PIE CHART - GENDER DISTRIBUTION**"""

fig = px.pie(
    df,
    names='sex',
    title='Gender Distribution'
)
fig.show()

"""**OBJECTIVE 9 : RISK ANALYSIS**"""

def risk_level(charges):
    if charges < 10000:
        return 'Low Cost'
    elif charges < 30000:
        return 'Medium Cost'
    else:
        return 'High Cost'
df['Risk_Level'] = df['charges'].apply(risk_level)
print(df.head())

"""**RISK LEVEL DISTRIBUTION**"""

fig = px.bar(
    df,
    x='Risk_Level',
    color='Risk_Level',
    title='Insurance Risk Dashboard',
    color_discrete_sequence=['#7B1C1C', '#C0504D', '#A52A2A']
)
fig.show()

"""**OBJECTIVE 10 : SIMPLE LINEAR REGRESSION**"""

X = df[['age']]
y = df['charges']
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
model_lr = LinearRegression()
model_lr.fit(X_train, y_train)
y_pred = model_lr.predict(X_test)
print("Simple Linear Regression Model Trained")

"""**LINEAR REGRESSION EVALUATION**"""

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("R2 Score :", r2)
print("MAE :", mae)
print("MSE :", mse)
print("RMSE :", rmse)

"""**LINEAR REGRESSION VISUALIZATION**"""

plt.figure(figsize=(8,5))
plt.scatter(X_test, y_test)
plt.plot(X_test, y_pred, color='red')
plt.title("Age vs Insurance Charges")
plt.xlabel("Age")
plt.ylabel("Charges")
plt.show()

"""**OBJECTIVE 11 : MULTIPLE LINEAR REGRESSION**"""



X = df[['age', 'bmi', 'children', 'smoker']]
y = df['charges']
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
mlr_model = LinearRegression()
mlr_model.fit(X_train, y_train)
y_pred_mlr = mlr_model.predict(X_test)
print("Multiple Linear Regression Completed")

"""**MULTIPLE LINEAR REGRESSION EVALUATION**"""

r2 = r2_score(y_test, y_pred_mlr)
mae = mean_absolute_error(y_test, y_pred_mlr)
mse = mean_squared_error(y_test, y_pred_mlr)
rmse = np.sqrt(mse)
print("R2 Score :", r2)
print("MAE :", mae)
print("MSE :", mse)
print("RMSE :", rmse)

"""**FEATURE IMPORTANCE**"""

importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': mlr_model.coef_
})
print(importance)

"""**ACTUAL VS PREDICTED VALUES**"""

results = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred_mlr
})
print(results.head())

"""**OBJECTIVE 12 : LOGISTIC REGRESSION**"""

median_charge = df['charges'].median()
df['insurance_category'] = np.where(
    df['charges'] > median_charge,
    1,
    0
)
print(df.head())

"""**FEATURES & TARGET**"""

X = df[['age', 'bmi', 'children', 'smoker']]
y = df['insurance_category']
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""**TRAIN LOGISTIC REGRESSION MODEL**"""

log_model = LogisticRegression()
log_model.fit(X_train, y_train)
y_pred_log = log_model.predict(X_test)
print("Logistic Regression Model Trained")

"""**OBJECTIVE 13 : MODEL EVALUATION**"""

accuracy = accuracy_score(y_test, y_pred_log)
print("Accuracy :", accuracy)

"""**CONFUSION MATRIX**"""

cm = confusion_matrix(y_test, y_pred_log)
print(cm)

"""**CONFUSION MATRIX HEATMAP**"""

sns.heatmap(cm, annot=True, fmt='d', cmap='Reds')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""**PRECISION, RECALL, F1 SCORE**"""

print("Precision :", precision_score(y_test, y_pred_log))
print("Recall :", recall_score(y_test, y_pred_log))
print("F1 Score :", f1_score(y_test, y_pred_log))

"""**CLASSIFICATION REPORT**"""

print(classification_report(y_test, y_pred_log))

"""**MODEL PERFORMANCE COMPARISON**"""

models = ['Linear Regression', 'Multiple Regression']
scores = [0.10, 0.75]
fig = px.bar(
    x=models,
    y=scores,
    title='Model Performance Comparison',
    color=scores
)
fig.show()

"""**OBJECTIVE 14 : INTERACTIVE DASHBOARD**"""

fig = px.scatter(
    df,
    x='age',
    y='charges',
    color='Risk_Level',
    size='bmi',
    hover_data=['children'],
    title='Medical Insurance Dashboard'
)
fig.show()

"""**REGION FILTER DASHBOARD**"""

fig = px.box(
    df,
    x='region',
    y='charges',
    color='Risk_Level',
    title='Region Wise Insurance Charges'
)
fig.show()

"""**GENDER VS CHARGES**"""

fig = px.bar(
    df,
    x='sex',
    y='charges',
    color='Risk_Level',
    title='Gender Wise Insurance Charges'
)
fig.show()

"""**SMOKER DASHBOARD**"""

fig = px.scatter(
    df,
    x='bmi',
    y='charges',
    color='smoker',
    title='Smoker vs Charges Dashboard'
)
fig.show()

"""**OBJECTIVE 15 : FINAL INSIGHTS & CONCLUSION**"""

print("============== FINAL INSIGHTS ==============")
print("1. Smoking significantly increases insurance charges.")
print("2. Age has a positive relationship with insurance premium.")
print("3. Customers with higher BMI tend to pay higher charges.")
print("4. Multiple Linear Regression performs better than Simple Linear Regression.")
print("5. Logistic Regression successfully classifies high-cost customers.")
print("6. Insurance companies can use this model for premium estimation.")
print("7. Dashboard helps identify high-risk customers quickly.")
print("8. Data visualization improves business understanding and decision-making.")
print("============== PROJECT COMPLETED SUCCESSFULLY ==============")